--- #YAML:1.0
name:               RPM-Search
version:            0.01
abstract:           Search all available RPMs
author:
    - Mark Allen <mrallen1@yahoo.com>
license:            perl_5
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:  0
    DBI:          0
    File::Find:   0
    Test::More:   0
    Try::Tiny:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
